# Generated by Django 4.2.5 on 2023-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="photo",
            new_name="photo_url",
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
