# Generated by Django 4.2.5 on 2023-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_crud", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_available",
            new_name="in_stock",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("PR", "Processor"),
                    ("GC", "Graphics card"),
                    ("KB", "Keyboard"),
                    ("MS", "Mouse"),
                    ("SD", "SSD"),
                    ("MB", "Motherboard"),
                ],
                max_length=2,
            ),
        ),
    ]
